version = 0.1
[default]
[default.pipeline_bootstrap]
[default.pipeline_bootstrap.parameters]
pipeline_user = "arn:aws:iam::341014156608:user/aws-sam-cli-managed-dev-pipeline-reso-PipelineUser-YPSQG2EPCUGM"
permissions_provider = "AWS IAM"

[dev]
[dev.pipeline_bootstrap]
[dev.pipeline_bootstrap.parameters]
pipeline_execution_role = "arn:aws:iam::341014156608:role/aws-sam-cli-managed-dev-pipe-PipelineExecutionRole-OGMHL6NVQ00Y"
cloudformation_execution_role = "arn:aws:iam::341014156608:role/aws-sam-cli-managed-dev-p-CloudFormationExecutionR-BD1FOMZPSPHX"
artifacts_bucket = "aws-sam-cli-managed-dev-pipeline-artifactsbucket-1ugvcnyi2o9gg"
image_repository = ""
region = "ap-southeast-2"

[prod]
[prod.pipeline_bootstrap]
[prod.pipeline_bootstrap.parameters]
pipeline_execution_role = "arn:aws:iam::341014156608:role/aws-sam-cli-managed-prod-pip-PipelineExecutionRole-1FWX5R0QIUBYS"
cloudformation_execution_role = "arn:aws:iam::341014156608:role/aws-sam-cli-managed-prod-CloudFormationExecutionR-6O91E6M9PKEV"
artifacts_bucket = "aws-sam-cli-managed-prod-pipeline-artifactsbucket-v8a0ccl914yf"
image_repository = ""
region = "ap-southeast-2"
